contao:
    search:
        default_indexer:
            enable: false
    security:
        two_factor:
            enforce_backend: true
    localconfig:
        adminEmail: association@contao.org
        dateFormat: "d.m.Y"
        datimFormat: "d.m.Y H:i"
        timeZone: 'Europe/Zurich'

        # Adjust the upload image settings
        maxFileSize: 20480000
        imageWidth: 2500
        imageHeight: 2500

framework:
    assets:
        json_manifest_path: '%kernel.project_dir%/public/layout/manifest.json'
