parameters:
    memberships:
        active:
            price: 80
            custom: false
            group: 1
            categoryId: 5
            accountId: 43

        passive:
            price: 50
            custom: false
            group: 2
            categoryId: 6
            accountId: 151

        support:
            price: 200
            custom: true
            group: 3
            categoryId: 7
            accountId: 152

services:
    _defaults:
        autoconfigure: true
        autowire: true
        bind:
            $memberships: '%memberships%'
            $projectDir: '%kernel.project_dir%'

    App\:
        resource: ../src

    App\Controller\FrontendModule\RegistrationController:
        arguments:
            $notificationId: '%env(REGISTRATION_NOTIFICATION)%'

    App\Cron\ActivateMemberCron:
        arguments:
            $notificationId: '%env(ACTIVATION_NOTIFICATION)%'

    App\Cron\RecurringInvoicesCron:
        arguments:
            $notificationId: '%env(RECURRING_NOTIFICATION)%'

    App\Cron\PaymentNotificationCron:
        arguments:
            $notificationId: '%env(PAYMENT_NOTIFICATION)%'
