parameters:
    memberships:
        support5:
            price: 5
            type: month
            custom: false
            group: 4
            categoryId: 8
            accountId: 183

        support10:
            price: 10
            type: month
            custom: false
            group: 4
            categoryId: 8
            accountId: 183

        support25:
            price: 25
            type: month
            custom: false
            group: 4
            memberGroup: 1
            categoryId: 8
            accountId: 183

        support50:
            price: 50
            type: month
            custom: false
            group: 4
            memberGroup: 1
            categoryId: 8
            accountId: 183

        sponsor:
            price: 100
            type: month
            custom: false
            group: 5
            memberGroup: 1
            categoryId: 9
            accountId: 183

        gold_sponsor:
            price: 200
            type: month
            custom: false
            group: 6
            memberGroup: 1
            categoryId: 10
            accountId: 183

        diamond_sponsor:
            price: 500
            type: month
            custom: false
            group: 7
            memberGroup: 1
            categoryId: 11
            accountId: 183

        active:
            price: 80
            type: year
            custom: false
            group: 1
            categoryId: 5
            accountId: 43

        passive:
            price: 50
            type: year
            custom: false
            group: 2
            categoryId: 6
            accountId: 151
            legacy: true

        support:
            price: 200
            type: custom
            custom: true
            group: 3
            categoryId: 7
            accountId: 152
            legacy: true

services:
    _defaults:
        autoconfigure: true
        autowire: true
        bind:
            $memberships: '%memberships%'
            $projectDir: '%kernel.project_dir%'

    App\:
        resource: ../src

    App\Command\RecurringInvoicesCommand:
        arguments:
            $notificationId: '%env(RECURRING_NOTIFICATION)%'

    App\Controller\FrontendModule\InvoicesController:
        arguments:
            $harvestId: '%env(HARVEST_ID)%'
            $harvestToken: '%env(HARVEST_TOKEN)%'

    App\Controller\FrontendModule\RegistrationController:
        arguments:
            $notificationId: '%env(REGISTRATION_NOTIFICATION)%'

    App\Controller\Webhooks\KofiController:
        arguments:
            $kofiToken: '%env(KOFI_TOKEN)%'
        tags:
            - controller.service_arguments

    App\Controller\Webhooks\PretixController:
        tags:
            - controller.service_arguments

    App\Controller\Webhooks\StripeController:
        arguments:
            $stripeSecret: '%env(STRIPE_SECRET)%'
        tags:
            - controller.service_arguments

    App\Cron\ActivateMemberCron:
        arguments:
            $notificationId: '%env(ACTIVATION_NOTIFICATION)%'

    App\Cron\RecurringInvoicesCron:
        arguments:
            $notificationId: '%env(RECURRING_NOTIFICATION)%'

    App\Cron\PaymentNotificationCron:
        arguments:
            $notificationId: '%env(PAYMENT_NOTIFICATION)%'

    App\RapidmailHelper:
        arguments:
            - '%env(RAPIDMAIL_USERNAME)%'
            - '%env(RAPIDMAIL_PASSWORD)%'
            - '%env(RAPIDMAIL_LIST)%'

    App\PretixHelper:
        arguments:
            $pretixToken: '%env(PRETIX_TOKEN)%'

    Stripe\StripeClient:
        arguments:
            - '%env(STRIPE_KEY)%'
