parameters:
    memberships:
        active:
            price: 80
            custom: false
            group: 1
            type: Aktivmitglied
            accountId: 43

        passive:
            price: 50
            custom: false
            group: 2
            type: Passivmitglied
            accountId: 151

        support:
            price: 200
            custom: true
            group: 3
            type: Fördermitglied
            accountId: 152

services:
    _defaults:
        autoconfigure: true
        autowire: true
        bind:
            $memberships: '%memberships%'
            $projectDir: '%kernel.project_dir%'

    App\:
        resource: ../src
