parameters:
    memberships:
        support5:
            price: 5
            type: month
            custom: false
            group: 4
            categoryId: 8
            accountId: 183

        support10:
            price: 10
            type: month
            custom: false
            group: 4
            categoryId: 8
            accountId: 183
            listing:
                name: supporter

        support25:
            price: 25
            type: month
            custom: false
            group: 4
            freeMember: true
            categoryId: 8
            accountId: 183
            listing:
                name: supporter
                link: true

        support50:
            price: 50
            type: month
            custom: false
            group: 4
            freeMember: true
            categoryId: 8
            accountId: 183
            listing:
                name: supporter
                link: true
                cloud: true

        sponsor:
            price: 100
            type: month
            custom: false
            group: 5
            freeMember: true
            categoryId: 9
            accountId: 183
            listing:
                name: sponsor
                link: true
                cloud: true
                logo: true
                video: name

        gold_sponsor:
            price: 200
            type: month
            custom: false
            group: 6
            freeMember: true
            categoryId: 10
            accountId: 183
            listing:
                name: gold_sponsor
                link: true
                cloud: true
                logo: true
                video: logo

        diamond_sponsor:
            price: 500
            type: month
            custom: false
            group: 7
            freeMember: true
            categoryId: 11
            accountId: 183
            listing:
                name: diamond_sponsor
                link: true
                cloud: true
                logo: true
                video: logo

        active:
            price: 80
            type: year
            custom: false
            group: 1
            categoryId: 5
            accountId: 43

        passive:
            price: 50
            type: year
            custom: false
            group: 2
            categoryId: 6
            accountId: 151
            legacy: true

        support:
            price: 200
            type: custom
            custom: true
            group: 3
            categoryId: 7
            accountId: 152
            legacy: true

services:
    _defaults:
        autoconfigure: true
        autowire: true
        bind:
            $memberships: '%memberships%'
            $projectDir: '%kernel.project_dir%'
            $registrationNotificationId: '%env(REGISTRATION_NOTIFICATION)%'
            $invoiceNotificationId: '%env(INVOICE_NOTIFICATION)%'
            $paymentNotificationId: '%env(PAYMENT_NOTIFICATION)%'

    App\:
        resource: ../src

    App\Controller\FrontendModule\InvoicesController:
        arguments:
            $harvestId: '%env(HARVEST_ID)%'
            $harvestToken: '%env(HARVEST_TOKEN)%'

    App\Controller\Webhooks\KofiController:
        arguments:
            $kofiToken: '%env(KOFI_TOKEN)%'
        tags:
            - controller.service_arguments

    App\Controller\Webhooks\PretixController:
        tags:
            - controller.service_arguments

    App\Controller\Webhooks\StripeController:
        arguments:
            $stripeSecret: '%env(STRIPE_SECRET)%'
        tags:
            - controller.service_arguments

    App\RapidmailHelper:
        arguments:
            - '%env(RAPIDMAIL_USERNAME)%'
            - '%env(RAPIDMAIL_PASSWORD)%'
            - '%env(RAPIDMAIL_LIST)%'

    App\PaypalHelper:
        arguments:
            $teamMembers: '%env(PAYPAL_TEAM)%'

    App\PretixHelper:
        arguments:
            $pretixToken: '%env(PRETIX_TOKEN)%'

    Stripe\StripeClient:
        arguments:
            - '%env(STRIPE_KEY)%'

    PayPalCheckoutSdk\Core\PayPalHttpClient:
        arguments:
            - !service
              class: PayPalCheckoutSdk\Core\ProductionEnvironment
              arguments:
                  - '%env(PAYPAL_CLIENT_ID)%'
                  - '%env(PAYPAL_SECRET)%'
